### ISSUE TITLE
update from iframe-template code then split off own version

### ISSUE THREAD

**Issue by russellsamora** [BostonGlobe/slush-globegraphic#13]

**Comment by gabrielflorit** [comment]
- Created [slushgraphic-template](https://github.com/BostonGlobe/slushgraphic-template), a kitchen-sink iframe starter project.
- This repo now includes [slushgraphic-template](https://github.com/BostonGlobe/slushgraphic-template) as a git subtree in the [/template](https://github.com/BostonGlobe/slush-globegraphic/tree/master/template) directory.
